make nav buttons larger and remove outline on back save and edit buttons
Code2Gether-Discord/subtrack pull request #143
Opened 2023-09-20 09:01 UTC by Penguine-Os

Closes #91

2023-09-20 09:12 UTC, chrisK00 reviewed
Would you mind posting a screenshot of the home page?

2023-09-20 16:57 UTC, chrisK00 commented
About the nav buttons
- Can we make the buttons close to each other again and centered so the user doesnt have to move their thumb to the other end of the screen
- Add some space to the bottom of the buttons, its quite easy to missclick and click the androids back/home/open apps buttons.
- Remove the -fill from the calendar icon so its consistent with the home button
- Also add a tiny bit of space above the icons (the line above them is too close)
- You can make the icons a tiny bit smaller
- When you push the icons from the upper divider or from the bottom, use padding on the buttons so that they are easily clicked

2023-09-21 04:12 UTC, Penguine-Os commented
![afbeelding](https://github.com/Code2Gether-Discord/subtrack/assets/24791504/352c7fb4-8fca-4edf-82b7-a77bff45ca6d)

2023-09-21 07:10 UTC, chrisK00 commented
> ![afbeelding](https://github.com/Code2Gether-Discord/subtrack/assets/24791504/352c7fb4-8fca-4edf-82b7-a77bff45ca6d)
> 

Space above looks good on this img. Is this be4/after my comment

2023-09-23 15:17 UTC, chrisK00 requested changes

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
> +<nav class="navbar navbar-expand bg-dark fixed-bottom custom-navbar" data-bs-theme="dark">
```suggestion
<nav class="navbar navbar-expand bg-dark fixed-bottom custom-navbar justify-content-center" data-bs-theme="dark">
```

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
> +    <ul class="nav navbar-nav flex w-100 justify-content-around">
```suggestion
    <ul class="navbar-nav">
```

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
>              <li class="nav-item">
```suggestion
            <li class="nav-item ms-4">
```

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
> +                    <i class="bi bi-calendar2-week-fill" style="font-size: 1.75rem;"></i>
```suggestion
                    <i class="bi bi-calendar" style="font-size: 1.65rem;"></i>
```

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
> +                    <i class="bi bi-house" style="font-size: 1.75rem;"></i>
```suggestion
                    <i class="bi bi-house" style="font-size: 1.65rem;"></i>
```

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
>                  <NavLink class="nav-link d-flex flex-column align-items-center" href="monthly" Match="NavLinkMatch.Prefix">
```suggestion
                <NavLink class="nav-link d-flex flex-column align-items-center pb-4 px-2" href="monthly" Match="NavLinkMatch.Prefix">
```

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
>                  <NavLink class="nav-link d-flex flex-column align-items-center" href="/" Match="NavLinkMatch.All">
```suggestion
                <NavLink class="nav-link d-flex flex-column align-items-center pb-4 px-2" href="/" Match="NavLinkMatch.All">
```

2023-09-23 15:17 UTC, chrisK00 commented on subtrack.MAUI/Shared/NavBar.razor
> +        height: 3rem; /* Adjust the height value as needed */
```suggestion
        height: 4.1rem; /* Adjust the height value as needed */
```

2023-09-23 15:17 UTC, chrisK00 commented
![qemu-system-x86_64_3cHNwuKScZ](https://github.com/Code2Gether-Discord/subtrack/assets/72318023/3e310031-8ab0-4d0d-a82a-6da2846ef715)
After my suggested changes

2023-09-24 09:47 UTC, chrisK00 commented
closes #134

2023-09-24 09:49 UTC, chrisK00 approved these changes

2023-09-24 10:08 UTC, merged