Adds subscription icon and secondary color
Code2Gether-Discord/subtrack pull request #149
Opened 2023-09-28 12:45 UTC by ashwin003

Closes #132

2023-09-28 14:35 UTC, chrisK00 requested changes
Really nice PR to review, the only thing I can give feedback on is design stuff🔥

- Center the icon above the title on details page. so you can directly make the title move down one line

Upsert page
- Type "Icon" before the icon picker since when the value is null there is nothing explaining what the button does
- Align the secondary color picker with primary color selector, alternatively move the secondary color selector down one line and type "secondary color" before it
- When the secondary color is changed - can we change the icon picker color button to have the same color?

2023-09-29 06:31 UTC, chrisK00 requested changes

2023-09-29 06:31 UTC, chrisK00 commented on subtrack.MAUI/Utilities/CssUtil.cs
> +    internal static readonly IEnumerable<string> AvailableIcons = new[]
need a null/empty option in case the user wants to remove the icon

2023-09-29 06:31 UTC, chrisK00 commented on subtrack.MAUI/Pages/SubscriptionDetails.razor
>              <div>
I rewrote the code to make the icon larger, made the text use all available space in the container and centered both

You can just copy this all the way from the "container" (the line above this comment) to the first "row"

```
<div class="container">
    <div class="d-flex justify-content-between pt-2">
        <div>
            <BackButton Url="@ReturnUrl"></BackButton>
        </div>

        <div>
            @if (!string.IsNullOrWhiteSpace(_subscription.Icon))
            {
                <i class="@_subscription.Icon mt-1" style="color: @_subscription.SecondaryColor; font-size:30px"></i>
                <br />
            }
        </div>

        <div>
            <EditButton Url="@EditUrl"></EditButton>
        </div>
    </div>

    <div class="text-center">
        <h2 class="mt-1 text-break">@_subscription.Name</h2>
    </div>

    <div class="row py-2">
```

2023-09-29 06:31 UTC, chrisK00 commented on subtrack.MAUI/Pages/UpsertSubscription.razor
>      <div style="display: flex;">
```suggestion
    <div class="mt-2" style="display: flex;">
```

2023-09-29 06:31 UTC, chrisK00 commented on subtrack.MAUI/Pages/UpsertSubscription.razor
> +        <div class="d-flex flex-fill">
```suggestion
        <div class="d-flex flex-fill ms-2">
```

2023-09-29 06:31 UTC, chrisK00 commented on subtrack.MAUI/Pages/UpsertSubscription.razor
> +            <label style="white-space: nowrap; padding-right: 10px; font-size: 17px;" for="backgroundColor">Secondary Color </label>
```suggestion
<label class="pe-2" style="white-space: nowrap; font-size: 17px;" for="backgroundColor">Secondary Color </label>
```

2023-09-29 06:31 UTC, chrisK00 commented on subtrack.MAUI/Pages/UpsertSubscription.razor
> +            <label style="white-space: nowrap; padding-right: 10px; font-size: 17px;" for="backgroundColor">Primary Color </label>
```suggestion
<label class="pe-2" style="white-space: nowrap; font-size: 17px;" for="backgroundColor">Primary Color </label>            
```

2023-09-29 06:31 UTC, chrisK00 commented on subtrack.MAUI/Shared/Components/IconPicker.razor
> +<button type="button" class="btn btn-outline-primary @SelectedIcon" data-bs-toggle="modal" data-bs-target="#iconPickerModal" style="height: 100%;">
```suggestion
<button type="button" class="btn btn-outline-primary @SelectedIcon" data-bs-toggle="modal" data-bs-target="#iconPickerModal" style="height: 100%; min-height: 25px;">
```

2023-09-29 09:12 UTC, ashwin003 commented on subtrack.MAUI/Pages/SubscriptionDetails.razor
>              <div>
this also moves the title to the next line even if there is no icon to display.

![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/dc34e6bd-76fd-457b-9fc5-65c058028f93)

2023-09-29 09:13 UTC, ashwin003 commented on subtrack.MAUI/Utilities/CssUtil.cs
> +    internal static readonly IEnumerable<string> AvailableIcons = new[]
Alternative option: A button to clear the icon

![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/26163d70-983f-46fc-a248-621bd8eb549f)

2023-09-29 09:14 UTC, ashwin003 commented on subtrack.MAUI/Shared/Components/IconPicker.razor
> +<button type="button" class="btn btn-outline-primary @SelectedIcon" data-bs-toggle="modal" data-bs-target="#iconPickerModal" style="height: 100%;">
Done

2023-09-29 09:15 UTC, ashwin003 commented on subtrack.MAUI/Pages/UpsertSubscription.razor
> +            <label style="white-space: nowrap; padding-right: 10px; font-size: 17px;" for="backgroundColor">Secondary Color </label>
Done

2023-09-29 09:15 UTC, ashwin003 commented on subtrack.MAUI/Pages/UpsertSubscription.razor
> +        <div class="d-flex flex-fill">
Done

2023-09-29 09:15 UTC, ashwin003 commented on subtrack.MAUI/Pages/UpsertSubscription.razor
>      <div style="display: flex;">
Done

2023-09-29 09:51 UTC, chrisK00 commented on subtrack.MAUI/Utilities/CssUtil.cs
> +    internal static readonly IEnumerable<string> AvailableIcons = new[]
> Alternative option: A button to clear the icon
> 
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/26163d70-983f-46fc-a248-621bd8eb549f)
> 

Thats better

2023-09-29 09:52 UTC, chrisK00 commented on subtrack.MAUI/Pages/SubscriptionDetails.razor
>              <div>
True but its not an issue, it allows for longer titles in one line

2023-09-29 10:14 UTC, ashwin003 commented on subtrack.MAUI/Pages/SubscriptionDetails.razor
>              <div>
Done

2023-09-29 15:20 UTC, chrisK00 approved these changes

2023-09-29 21:50 UTC, merged