Feature/calculate total cost of subscriptions for a specific month
Code2Gether-Discord/subtrack pull request #25
Opened 2023-06-26 17:31 UTC by Pituzek

Confused a bit, so ready for a discussion :)

2023-06-26 18:03 UTC, chrisK00 requested changes

2023-06-26 18:03 UTC, chrisK00 commented on .gitignore
> +/subtrack.DAL/Migrations/20230626155241_myFirstMigration.cs
Dont think this should be comitted

2023-06-26 18:03 UTC, chrisK00 commented on subtrack.MAUI/Services/SubscriptionsCalculator.cs
> +    public static List<Subscription> GetSubscriptionListByMonth(IEnumerable<Subscription> subscriptions, DateTime localDate)
```suggestion
    public static IEnumerable<Subscription> GetDueSubscriptionsByMonth(IEnumerable<Subscription> subscriptions, DateTime monthDate)
```

2023-06-26 18:03 UTC, chrisK00 commented on subtrack.MAUI/Services/SubscriptionsCalculator.cs
> +        var subscriptionsByMonth = GetSubscriptionListByMonth(subscriptions, DateTime.Now);
Theres no reason for calling GetSubscriptionListByMonth here

1. all the subscriptions sent in to this method will return the cost for them. 
2. This is used by the startpage which might list all subscriptions even if they are not to be paid this month

Might be a good idea to rename this method to just GetCost

2023-06-26 18:03 UTC, chrisK00 commented on subtrack.MAUI/Response/SubscriptionsMonthResponse.cs
> +    public class SubscriptionsMonthResponse
add a prop called cost for this month's cost

2023-06-26 18:03 UTC, chrisK00 commented on subtrack.MAUI/Response/SubscriptionsMonthResponse.cs
> +        public IEnumerable<Subscription> Subscriptions { get; }
duplicated list, only need the responses

2023-06-26 18:03 UTC, chrisK00 commented on subtrack.MAUI/Response/SubscriptionsMonthResponse.cs
> +        public IEnumerable<SubscriptionResponse> Map(IEnumerable<Subscription> Subscriptions)
Extract the mapping code to its own class/existing mapping class, make use of Linq select statement instead of creating a new list

2023-06-26 18:03 UTC, chrisK00 commented on subtrack.MAUI/Response/SubscriptionsMonthResponse.cs
> +        public IEnumerable<SubscriptionResponse> GetSubscriptionCostByMonth()
This method can be removed. The view can call the method for getting the correct subs and calculating the cost itself and then another one to map them.

2023-06-27 16:02 UTC, chrisK00 requested changes

2023-06-27 16:02 UTC, chrisK00 commented on subtrack.MAUI/Mappers/SubscriptionMapper.cs
> +        public IEnumerable<SubscriptionResponse> Map(IEnumerable<Subscription> subscriptions)
```suggestion
        public static IEnumerable<SubscriptionResponse> ToResponses(this IEnumerable<Subscription> subscriptions)
```

2023-06-27 16:02 UTC, chrisK00 commented on subtrack.MAUI/Mappers/SubscriptionMapper.cs
> +    public class SubscriptionMapper
```suggestion
    public static class SubscriptionMapper
```

2023-06-27 16:02 UTC, chrisK00 commented on subtrack.MAUI/Mappers/SubscriptionMapper.cs
> +        public IEnumerable<SubscriptionResponse> Map(IEnumerable<Subscription> subscriptions)
Usage: subscriptions.ToResponses()

2023-06-27 16:02 UTC, chrisK00 commented on subtrack.MAUI/Response/SubscriptionsMonthResponse.cs
> +        public IEnumerable<SubscriptionResponse> SubscriptionResponse { get; }
```suggestion
        public IEnumerable<SubscriptionResponse> SubscriptionResponses { get; set; }
```

2023-06-27 16:02 UTC, chrisK00 commented on subtrack.MAUI/Response/SubscriptionsMonthResponse.cs
> +        public SubscriptionsMonthResponse(DateTime dateTime)
can be removed

2023-06-27 16:02 UTC, chrisK00 commented on subtrack.MAUI/Response/SubscriptionsMonthResponse.cs
> +namespace subtrack.MAUI.Response
Move subscriptionsresponse.cs to this folder

2023-06-28 20:22 UTC, Memsworth requested changes, later dismissed

2023-06-28 20:22 UTC, Memsworth commented on subtrack.MAUI/Mappers/SubscriptionMapper.cs
> +        public static IEnumerable<SubscriptionResponse> ToResponses(this IEnumerable<Subscription> subscriptions)
Subscription Mapper implemented in pull request: #22

2023-06-28 20:22 UTC, Memsworth commented on subtrack.MAUI/Response/SubscriptionResponse.cs
> +    public class SubscriptionResponse
Class implemented in pull request: #22

2023-06-28 23:27 UTC, Pituzek commented
Applied some cleanup

2023-06-29 19:53 UTC, chrisK00 requested changes

2023-06-29 19:53 UTC, chrisK00 commented on subtrack.MAUI/Responses/SubscriptionResponse.cs
>          public Subscription Subscription { get; set; }
We have all info the subscription has, do we actually need to keep the prop?

2023-06-29 19:53 UTC, chrisK00 commented on subtrack.Tests/SubscriptionCalculatorTests/GetSubscriptionListByMonthTests.cs
> +        public void GetSubscriptionListByMonth_MonthProvided_ReturnsUnpaidSubscriptions()
Make this two test cases instead and create the list of subscriptions directly here.

_MonthProvided_ShouldNotReturn_PaidSubscriptions

2023-07-01 20:41 UTC, chrisK00 approved these changes
Well done!

2023-07-01 20:56 UTC, merged